In [2]:
import pandapower as pp
import pandapower.networks as pn
import pandas as pd
import numpy as np
import os
import sys
import networkx as nx
import matplotlib.pyplot as plt

In [3]:
net_real = pn.case118()

In [4]:
net_real

This pandapower network includes the following parameter tables:
   - bus (118 elements)
   - load (99 elements)
   - gen (53 elements)
   - shunt (14 elements)
   - ext_grid (1 element)
   - line (173 elements)
   - trafo (13 elements)
   - poly_cost (54 elements)

In [5]:
net_real.ext_grid

,name,bus,vm_pu,va_degree,slack_weight,in_service,max_p_mw,min_p_mw,max_q_mvar,min_q_mvar
0,None,68,1.035,30.0,1.0,True,805.2,0.0,300.0,-300.0

In [6]:
net_real.gen

,name,bus,p_mw,vm_pu,sn_mva,min_q_mvar,max_q_mvar,scaling,slack,in_service,slack_weight,type,controllable,max_p_mw,min_p_mw,id_q_capability_characteristic,reactive_capability_curve,curve_style
0,None,0,0.0,0.955,NaN,-5.0,15.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
1,None,3,0.0,0.998,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
2,None,5,0.0,0.990,NaN,-13.0,50.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
3,None,7,0.0,1.015,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
4,None,9,450.0,1.050,NaN,-147.0,200.0,1.0,False,True,0.0,None,True,550.0,0.0,<NA>,False,None
5,None,11,85.0,0.990,NaN,-35.0,120.0,1.0,False,True,0.0,None,True,185.0,0.0,<NA>,False,None
6,None,14,0.0,0.970,NaN,-10.0,30.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
7,None,17,0.0,0.973,NaN,-16.0,50.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
8,None,18,0.0,0.962,NaN,-8.0,24.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
9,None,23,0.0,0.992,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
10,None,24,220.0,1.050,NaN,-47.0,140.0,1.0,False,True,0.0,None,True,320.0,0.0,<NA>,False,None
11,None,25,314.0,1.015,NaN,-1000.0,1000.0,1.0,False,True,0.0,None,True,414.0,0.0,<NA>,False,None
12,None,26,0.0,0.968,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
13,None,30,7.0,0.967,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,107.0,0.0,<NA>,False,None
14,None,31,0.0,0.963,NaN,-14.0,42.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
15,None,33,0.0,0.984,NaN,-8.0,24.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
16,None,35,0.0,0.980,NaN,-8.0,24.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
17,None,39,0.0,0.970,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
18,None,41,0.0,0.985,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
19,None,45,19.0,1.005,NaN,-100.0,100.0,1.0,False,True,0.0,None,True,119.0,0.0,<NA>,False,None
20,None,48,204.0,1.025,NaN,-85.0,210.0,1.0,False,True,0.0,None,True,304.0,0.0,<NA>,False,None
21,None,53,48.0,0.955,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,148.0,0.0,<NA>,False,None
22,None,54,0.0,0.952,NaN,-8.0,23.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
23,None,55,0.0,0.954,NaN,-8.0,15.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
24,None,58,155.0,0.985,NaN,-60.0,180.0,1.0,False,True,0.0,None,True,255.0,0.0,<NA>,False,None
25,None,60,160.0,0.995,NaN,-100.0,300.0,1.0,False,True,0.0,None,True,260.0,0.0,<NA>,False,None
26,None,61,0.0,0.998,NaN,-20.0,20.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
27,None,64,391.0,1.005,NaN,-67.0,200.0,1.0,False,True,0.0,None,True,491.0,0.0,<NA>,False,None
28,None,65,392.0,1.050,NaN,-67.0,200.0,1.0,False,True,0.0,None,True,492.0,0.0,<NA>,False,None
29,None,69,0.0,0.984,NaN,-10.0,32.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
30,None,71,0.0,0.980,NaN,-100.0,100.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
31,None,72,0.0,0.991,NaN,-100.0,100.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
32,None,73,0.0,0.958,NaN,-6.0,9.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
33,None,75,0.0,0.943,NaN,-8.0,23.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
34,None,76,0.0,1.006,NaN,-20.0,70.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
35,None,79,477.0,1.040,NaN,-165.0,280.0,1.0,False,True,0.0,None,True,577.0,0.0,<NA>,False,None
36,None,84,0.0,0.985,NaN,-8.0,23.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
37,None,86,4.0,1.015,NaN,-100.0,1000.0,1.0,False,True,0.0,None,True,104.0,0.0,<NA>,False,None
38,None,88,607.0,1.005,NaN,-210.0,300.0,1.0,False,True,0.0,None,True,707.0,0.0,<NA>,False,None
39,None,89,0.0,0.985,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
40,None,90,0.0,0.980,NaN,-100.0,100.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
41,None,91,0.0,0.990,NaN,-3.0,9.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
42,None,98,0.0,1.010,NaN,-100.0,100.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
43,None,99,252.0,1.017,NaN,-50.0,155.0,1.0,False,True,0.0,None,True,352.0,0.0,<NA>,False,None
44,None,102,40.0,1.010,NaN,-15.0,40.0,1.0,False,True,0.0,None,True,140.0,0.0,<NA>,False,None
45,None,103,0.0,0.971,NaN,-8.0,23.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
46,None,104,0.0,0.965,NaN,-8.0,23.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
47,None,106,0.0,0.952,NaN,-200.0,200.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
48,None,109,0.0,0.973,NaN,-8.0,23.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
49,None,110,36.0,0.980,NaN,-100.0,1000.0,1.0,False,True,0.0,None,True,136.0,0.0,<NA>,False,None
50,None,111,0.0,0.975,NaN,-100.0,1000.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
51,None,112,0.0,0.993,NaN,-100.0,200.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
52,None,115,0.0,1.005,NaN,-1000.0,1000.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None

In [4]:
net_real.load

,name,bus,p_mw,q_mvar,const_z_p_percent,const_z_q_percent,const_i_p_percent,const_i_q_percent,sn_mva,scaling,in_service,type,controllable
0,None,0,51.0,27.0,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False
1,None,1,20.0,9.0,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False
2,None,2,39.0,10.0,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False
3,None,3,39.0,12.0,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False
4,None,5,52.0,22.0,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,None,113,8.0,3.0,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False
95,None,114,22.0,7.0,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False
96,None,115,184.0,0.0,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False
97,None,116,20.0,8.0,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False
98,None,117,33.0,15.0,0.0,0.0,0.0,0.0,NaN,1.0,True,None,False

In [5]:
net_real.bus

,name,vn_kv,type,zone,in_service,max_vm_pu,min_vm_pu,geo
0,1,138.0,b,1.0,True,1.06,0.94,"{""coordinates"": [-2.2753708781, 2.8543413351],..."
1,2,138.0,b,1.0,True,1.06,0.94,"{""coordinates"": [-2.9368186836, 2.2121792656],..."
2,3,138.0,b,1.0,True,1.06,0.94,"{""coordinates"": [-1.8344312496, 1.7094451782],..."
3,4,138.0,b,1.0,True,1.06,0.94,"{""coordinates"": [-0.8886268958, 1.5532705585],..."
4,5,138.0,b,1.0,True,1.06,0.94,"{""coordinates"": [-0.9632829393, 0.694729907], ..."
...,...,...,...,...,...,...,...,...
113,114,138.0,b,1.0,True,1.06,0.94,"{""coordinates"": [2.2630604919, -2.7868829987],..."
114,115,138.0,b,1.0,True,1.06,0.94,"{""coordinates"": [3.1644478736, -2.3853607175],..."
115,116,345.0,b,1.0,True,1.06,0.94,"{""coordinates"": [-4.1528539003, -4.9348933434]..."
116,117,138.0,b,1.0,True,1.06,0.94,"{""coordinates"": [-3.5172125372, 1.7774067282],..."
117,118,138.0,b,1.0,True,1.06,0.94,"{""coordinates"": [-2.1457808291, -8.5466991795]..."

In [6]:
net_real.gen

,name,bus,p_mw,vm_pu,sn_mva,min_q_mvar,max_q_mvar,scaling,slack,in_service,slack_weight,type,controllable,max_p_mw,min_p_mw,id_q_capability_characteristic,reactive_capability_curve,curve_style
0,None,0,0.0,0.955,NaN,-5.0,15.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
1,None,3,0.0,0.998,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
2,None,5,0.0,0.990,NaN,-13.0,50.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
3,None,7,0.0,1.015,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
4,None,9,450.0,1.050,NaN,-147.0,200.0,1.0,False,True,0.0,None,True,550.0,0.0,<NA>,False,None
5,None,11,85.0,0.990,NaN,-35.0,120.0,1.0,False,True,0.0,None,True,185.0,0.0,<NA>,False,None
6,None,14,0.0,0.970,NaN,-10.0,30.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
7,None,17,0.0,0.973,NaN,-16.0,50.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
8,None,18,0.0,0.962,NaN,-8.0,24.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
9,None,23,0.0,0.992,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
10,None,24,220.0,1.050,NaN,-47.0,140.0,1.0,False,True,0.0,None,True,320.0,0.0,<NA>,False,None
11,None,25,314.0,1.015,NaN,-1000.0,1000.0,1.0,False,True,0.0,None,True,414.0,0.0,<NA>,False,None
12,None,26,0.0,0.968,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
13,None,30,7.0,0.967,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,107.0,0.0,<NA>,False,None
14,None,31,0.0,0.963,NaN,-14.0,42.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
15,None,33,0.0,0.984,NaN,-8.0,24.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
16,None,35,0.0,0.980,NaN,-8.0,24.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
17,None,39,0.0,0.970,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
18,None,41,0.0,0.985,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
19,None,45,19.0,1.005,NaN,-100.0,100.0,1.0,False,True,0.0,None,True,119.0,0.0,<NA>,False,None
20,None,48,204.0,1.025,NaN,-85.0,210.0,1.0,False,True,0.0,None,True,304.0,0.0,<NA>,False,None
21,None,53,48.0,0.955,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,148.0,0.0,<NA>,False,None
22,None,54,0.0,0.952,NaN,-8.0,23.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
23,None,55,0.0,0.954,NaN,-8.0,15.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
24,None,58,155.0,0.985,NaN,-60.0,180.0,1.0,False,True,0.0,None,True,255.0,0.0,<NA>,False,None
25,None,60,160.0,0.995,NaN,-100.0,300.0,1.0,False,True,0.0,None,True,260.0,0.0,<NA>,False,None
26,None,61,0.0,0.998,NaN,-20.0,20.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
27,None,64,391.0,1.005,NaN,-67.0,200.0,1.0,False,True,0.0,None,True,491.0,0.0,<NA>,False,None
28,None,65,392.0,1.050,NaN,-67.0,200.0,1.0,False,True,0.0,None,True,492.0,0.0,<NA>,False,None
29,None,69,0.0,0.984,NaN,-10.0,32.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
30,None,71,0.0,0.980,NaN,-100.0,100.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
31,None,72,0.0,0.991,NaN,-100.0,100.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
32,None,73,0.0,0.958,NaN,-6.0,9.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
33,None,75,0.0,0.943,NaN,-8.0,23.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
34,None,76,0.0,1.006,NaN,-20.0,70.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
35,None,79,477.0,1.040,NaN,-165.0,280.0,1.0,False,True,0.0,None,True,577.0,0.0,<NA>,False,None
36,None,84,0.0,0.985,NaN,-8.0,23.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
37,None,86,4.0,1.015,NaN,-100.0,1000.0,1.0,False,True,0.0,None,True,104.0,0.0,<NA>,False,None
38,None,88,607.0,1.005,NaN,-210.0,300.0,1.0,False,True,0.0,None,True,707.0,0.0,<NA>,False,None
39,None,89,0.0,0.985,NaN,-300.0,300.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
40,None,90,0.0,0.980,NaN,-100.0,100.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
41,None,91,0.0,0.990,NaN,-3.0,9.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
42,None,98,0.0,1.010,NaN,-100.0,100.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
43,None,99,252.0,1.017,NaN,-50.0,155.0,1.0,False,True,0.0,None,True,352.0,0.0,<NA>,False,None
44,None,102,40.0,1.010,NaN,-15.0,40.0,1.0,False,True,0.0,None,True,140.0,0.0,<NA>,False,None
45,None,103,0.0,0.971,NaN,-8.0,23.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
46,None,104,0.0,0.965,NaN,-8.0,23.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
47,None,106,0.0,0.952,NaN,-200.0,200.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
48,None,109,0.0,0.973,NaN,-8.0,23.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
49,None,110,36.0,0.980,NaN,-100.0,1000.0,1.0,False,True,0.0,None,True,136.0,0.0,<NA>,False,None
50,None,111,0.0,0.975,NaN,-100.0,1000.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
51,None,112,0.0,0.993,NaN,-100.0,200.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None
52,None,115,0.0,1.005,NaN,-1000.0,1000.0,1.0,False,True,0.0,None,True,100.0,0.0,<NA>,False,None

In [7]:
pp.runpp(net_real)

In [8]:
net_real

This pandapower network includes the following parameter tables:
   - bus (118 elements)
   - load (99 elements)
   - gen (53 elements)
   - shunt (14 elements)
   - ext_grid (1 element)
   - line (173 elements)
   - trafo (13 elements)
   - poly_cost (54 elements)
 and the following results tables:
   - res_bus (118 elements)
   - res_line (173 elements)
   - res_trafo (13 elements)
   - res_ext_grid (1 element)
   - res_load (99 elements)
   - res_shunt (14 elements)
   - res_gen (53 elements)

In [9]:
bus_df = net_real.res_bus

In [10]:
bus_df

        vm_pu  va_degree   p_mw      q_mvar
0    0.955000  10.941479   51.0   30.104083
1    0.971393  11.481305   20.0    9.000000
2    0.967692  11.824922   39.0   10.000000
3    0.998000  15.542785   39.0   27.009349
4    1.001985  15.987868    0.0   40.158927
..        ...        ...    ...         ...
113  0.960093  14.699260    8.0    3.000000
114  0.960023  14.690971   22.0    7.000000
115  1.005000  27.111814  184.0 -213.043755
116  0.973824  10.916680   20.0    8.000000
117  0.949438  21.949671   33.0   15.000000

[118 rows x 4 columns]

In [11]:
from tabpfn import TabPFNRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [12]:
X = bus_df.iloc[:,[0,1,3]]
y = bus_df.iloc[:,2]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)

In [13]:
regressor = TabPFNRegressor()  # Uses TabPFN-2.5 weights, trained on synthetic data only.
# To use TabPFN v2:
# regressor = TabPFNRegressor.create_default_for_version(ModelVersion.V2)
regressor.fit(X_train, y_train)
# Predict on the test set
predictions = regressor.predict(X_test)
# Evaluate the model
mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)
print("Mean Squared Error (MSE):", mse)
print("R² Score:", r2)

Mean Squared Error (MSE): 16624.799464148542
R² Score: 0.22410034919519195

In [14]:
y_test

56      12.000000
89     163.000000
4        0.000000
45       9.000000
26      71.000000
116     20.000000
69      66.000000
10      70.000000
90      10.000000
73      68.000000
18      45.000000
111     68.000000
11     -38.000000
96      15.000000
42      18.000000
31      59.000000
88    -607.000000
0       51.000000
97      34.000000
109     39.000000
64    -391.000000
40      37.000000
95      38.000000
53      65.000000
44      53.000000
12      34.000000
15      25.000000
70       0.000000
107      2.000000
24    -220.000000
66      28.000000
22       7.000000
36       0.000000
55      84.000000
81      54.000000
30      36.000000
62       0.000000
72       6.000000
9     -450.000000
33      59.000000
105     43.000000
68    -514.169694
28      24.000000
47      20.000000
84      24.000000
5       52.000000
77      71.000000
67       0.000000
39      66.000000
49      17.000000
35      31.000000
16      11.000000
65    -353.000000
34      33.000000
85      21.000000
7       28.000000
43      16.000000
112      6.000000
78      39.000000
Name: p_mw, dtype: float64

In [15]:
predictions

array([  15.32463 ,  -19.756878,  -11.847473,   22.792267,   27.43535 ,
         28.76678 ,   27.839592,   50.840878,   33.246536,   45.957638,
         41.32815 ,   33.752243,  -16.574932,   25.441296,   26.512508,
         41.50999 ,   14.35567 ,   58.926254,   20.740646,   48.98822 ,
          1.147481,   33.722767,   36.366196,   56.320465,   33.597893,
         42.522438,   31.496048,    8.679177,   11.707876, -159.60034 ,
         21.856287,   18.05299 ,   50.981483,   47.58216 ,   22.372536,
         24.629087,   10.29434 ,   -6.545429, -131.64186 ,   56.536133,
         38.499138, -149.63287 ,   20.439768,   -4.08533 ,   40.013977,
         25.879898,   41.24579 ,    6.147344,   29.402275,   21.166069,
         30.472755,   20.655329,   17.655233,   30.289345,   26.491062,
        -92.14103 ,   13.299029,    8.381475,   32.094555], dtype=float32)

In [16]:
from sklearn.datasets import load_diabetes
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from tabpfn import TabPFNRegressor
from tabpfn.constants import ModelVersion

# Load example dataset
X, y = load_diabetes(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# Initialize and fit
model = TabPFNRegressor(device="auto")
# To use TabPFNv2:
# model = TabPFNRegressor.create_default_for_version(ModelVersion.V2)
model.fit(X_train, y_train)

# Predict
preds = model.predict(X_test)

# Evaluate
print("MSE:", mean_squared_error(y_test, preds))
print("MAE:", mean_absolute_error(y_test, preds))
print("R²:", r2_score(y_test, preds))

MSE: 2652.501080916834
MAE: 40.96149528189881
R²: 0.5391170637609461

In [17]:
# Import all required components for data handling, feature engineering, and prediction
from datasets import load_dataset
from tabpfn_time_series import TimeSeriesDataFrame, FeatureTransformer, TabPFNTimeSeriesPredictor, TabPFNMode
from tabpfn_time_series.data_preparation import to_gluonts_univariate, generate_test_X
from tabpfn_time_series.features import RunningIndexFeature, CalendarFeature, AutoSeasonalFeature

# Choose dataset and define forecast horizon
ds, pred_len = "monash_tourism_monthly", 24

# Load dataset from Hugging Face and convert to a standard TimeSeriesDataFrame
raw = load_dataset("autogluon/chronos_datasets", ds)
tsdf = TimeSeriesDataFrame(to_gluonts_univariate(raw["train"]))

# Keep only the first 2 time series to keep the example lightweight
tsdf = tsdf[tsdf.index.get_level_values("item_id").isin(tsdf.item_ids[:2])]

# Split into training and test portions based on forecast horizon
train, _ = tsdf.train_test_split(prediction_length=pred_len)
test = generate_test_X(train, pred_len)

# Add useful temporal and seasonal features
features = [RunningIndexFeature(), CalendarFeature(), AutoSeasonalFeature()]
train, test = FeatureTransformer(features).transform(train, test)

# Initialize the predictor (client mode uses pretrained TabPFN weights) and generate forecasts
predictor = TabPFNTimeSeriesPredictor(tabpfn_mode=TabPFNMode.CLIENT)
pred = predictor.predict(train, test)

ModuleNotFoundError: No module named 'datasets'